
CREATE TABLE `books` (
  `isbn` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `author` varchar(255) NOT NULL,
  `about` varchar(500) NOT NULL,
  `price` varchar(500) NOT NULL,
  `genre` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `books`
  ADD PRIMARY KEY (`isbn`),
  ADD UNIQUE KEY `title` (`title`),
  ADD KEY `author` (`name`);
  ADD KEY `author` (`name`);
  ADD KEY `genre` (`genre`);

ALTER TABLE `books`
  MODIFY `isbn` int(11) NOT NULL AUTO_INCREMENT;


INSERT INTO `books` (`isbn`, `title`, `author`,`about`,`price`, `genre`) VALUES
(1000, 'Crying in H Mart: A Memoir','Michelle Zauner', 'INSTANT NEW YORK TIMES BEST SELLER - Named a Best Book of April 2021 by - AV Club - Bustle - Entertainment Weekly - Good Morning America - Chicago Review of Books - Fortune - TIME - CNN Underscored - Apartment Therapy - Popsugar - Hello Giggles - Business Insider - The Millions - Wall Street Journal Magazine - Glamour From the indie rockstar of Japanese Breakfast fame, and author of the viral 2018 New Yorker essay that shares the title of this book, an unflinching, powerful memoir about growing up Korean American, losing her mother, and forging her own identity. In this exquisite story of family, food, grief, and endurance, Michelle Zauner proves herself far more than a dazzling singer, songwriter, and guitarist. With humor and heart, she tells of growing up one of the few Asian American kids at her school in Eugene, Oregon; of struggling with her mothers particular, high expectations of her; of a painful adolescence; of treasured months spent in her grandmothers tiny apartment in Seoul, where she and her mother would bond, late at night, over heaping plates of food. As she grew up, moving to the East Coast for college, finding work in the restaurant industry, and performing gigs with her fledgling band--and meeting the man who would become her husband--her Koreanness began to feel ever more distant, even as she found the life she wanted to live. It was her mothers diagnosis of terminal cancer, when Michelle was twenty-five, that forced a reckoning with her identity and brought her to reclaim the gifts of taste, language, and history her mother had given her. Vivacious and plainspoken, lyrical and honest, Zauners voice is as radiantly alive on the page as it is onstage. Rich with intimate anecdotes that will resonate widely, and complete with family photos, Crying in H Mart is a book to cherish, share, and reread.

4.1 average based on 254 reviews.', '19.99', 'Memoir'),
(1001, 'Braiding Sweetgrass', 'Robin Wall Kimmerer', ' A New York Times Bestseller A Washington Post Bestseller Named a Best Essay Collection of the Decade by Literary Hub As a botanist, Robin Wall Kimmerer has been trained to ask questions of nature with the tools of science. As a member of the Citizen Potawatomi Nation, she embraces the notion that plants and animals are our oldest teachers. In Braiding Sweetgrass, Kimmerer brings these two lenses of knowledge together to take us on a journey that is every bit as mythic as it is scientific, as sacred as it is historical, as clever as it is wise (Elizabeth Gilbert). Drawing on her life as an indigenous scientist, and as a woman, Kimmerer shows how other living beings, asters and goldenrod, strawberries and squash, salamanders, algae, and sweetgrass--offer us gifts and lessons, even if we have forgotten how to hear their voices. In reflections that range from the creation of Turtle Island to the forces that threaten its flourishing today, she circles toward a central argument: that the awakening of ecological consciousness requires the acknowledgment and celebration of our reciprocal relationship with the rest of the living world. For only when we can hear the languages of other beings will we be capable of understanding the generosity of the earth, and learn to give our own gifts in return.

4.7 average based on 698 reviews.', '16.56', 'Science'),
(1002, 'How the Word Is Passed: A Reckoning with the History of Slavery Across America', 'Clint Smith', 'Instant #1 New York Times bestseller. "The Atlantic writer drafts a history of slavery in this country unlike anything you have read before. Beginning in his hometown of New Orleans, Clint Smith leads the reader on an unforgettable tour of monuments and landmarks--those that are honest about the past and those that are not--that offer an intergenerational story of how slavery has been central in shaping our nations collective history, and ourselves. It is the story of the Monticello Plantation in Virginia, the estate where Thomas Jefferson wrote letters espousing the urgent need for liberty while enslaving more than four hundred people. It is the story of the Whitney Plantation, one of the only former plantations devoted to preserving the experience of the enslaved people whose lives and work sustained it. It is the story of Angola, a former plantation-turned-maximum-security prison in Louisiana that is filled with Black men who work across the 18,000-acre land for virtually no pay. And it is the story of Blandford Cemetery, the final resting place of tens of thousands of Confederate soldiers. A deeply researched and transporting exploration of the legacy of slavery and its imprint on centuries of American history, How the Word Is Passed illustrates how some of our countrys most essential stories are hidden in plain view--whether in places we might drive by on our way to work, holidays such as Juneteenth, or entire neighborhoods like downtown Manhattan, where the brutal history of the trade in enslaved men, women, and children has been deeply imprinted. Informed by scholarship and brought to life by the story of people living today, Smith debut work of nonfiction is a landmark of reflection and insight that offers a new understanding of the hopeful role that memory and history can play in making sense of our country and how it has come to be.

4.8 average based on 335 reviews.', '26.68', 'History'), 

(1003, 'One Last Stop', 'Casey McQuiston', 'From the New York Times bestselling author of Red, White & Royal Blue comes a new romantic comedy that will stop readers in their tracks... For cynical twenty-three-year-old August, moving to New York City is supposed to prove her right: that things like magic and cinematic love stories do not exist, and the only smart way to go through life is alone. She cannot imagine how waiting tables at a 24-hour pancake diner and moving in with too many weird roommates could possibly change that. And theres certainly no chance of her subway commute being anything more than a daily trudge through boredom and electrical failures. But then, there is this gorgeous girl on the train. Jane. Dazzling, charming, mysterious, impossible Jane. Jane with her rough edges and swoopy hair and soft smile, showing up in a leather jacket to save Augusts day when she needed it most. Augusts subway crush becomes the best part of her day, but pretty soon, she discovers there is one big problem: Jane does not just look like an old school punk rocker. She is literally displaced in time from the 1970s, and August is going to have to use everything she tried to leave in her own past to help her. Maybe it is time to start believing in some things, after all. One Last Stop is a magical, big-hearted romance where the impossible becomes possible as August does everything in her power to save the girl lost in time. A dazzling romance, filled with plenty of humor and heart. - Time Magazine, The 21 Most Anticipated Books of 2021 Dreamy, other worldly, smart, swoony, thoughtful, hilarious - all in all, exactly what you would expect from Casey McQuiston! - Jasmine Guillory, New York Times bestselling author of The Proposal and Party for Two
4.4 average based on 654 reviews.', '15.63', 'Romance'),

(1004, 'Somebodys Daughter: A Memoir', 'Ashley C. Ford', 'One of the most prominent voices of her generation debuts with an extraordinarily powerful memoir: the story of a childhood defined by the looming absence of her incarcerated father. Through poverty, adolescence, and a fraught relationship with her mother, Ashley Ford wishes she could turn to her father for hope and encouragement. There are just a few problems: he is in prison, and she does not know what he did to end up there. She does not know how to deal with the incessant worries that keep her up at night, or how to handle the changes in her body that draw unwanted attention from men. In her search for unconditional love, Ashley begins dating a boy her mother hates. When the relationship turns sour, he assaults her. Still reeling from the rape, which she keeps secret from her family, Ashley desperately searches for meaning in the chaos. Then, her grandmother reveals the truth about her father incarceration . . . and Ashleys entire world is turned upside down. Somebodys Daughter steps into the world of growing up a poor Black girl in Indiana with a family fragmented by incarceration, exploring how isolating and complex such a childhood can be. As Ashley battles her body and her environment, she embarks on a powerful journey to find the threads between who she is and what she was born into, and the complicated familial love that often binds them.

4.9 average based on 994 reviews.', '25.75', 'Drama'),